package com.yty;

import com.yty.services.CommandLineRunnerService;
import com.yty.services.UserService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
public class Springboot008ContainerApplication implements CommandLineRunner {

    public static void main(String[] args) {
//        ConfigurableApplicationContext run = SpringApplication.run(Springboot008ContainerApplication.class, args);
//        UserService userServiceImpl = run.getBean("userServiceImpl", UserService.class);
//        userServiceImpl.select();
//        userServiceImpl.update();
        ConfigurableApplicationContext run = SpringApplication.run(Springboot008ContainerApplication.class, args);
        CommandLineRunnerService commandLineRunnerService = run.getBean("commandLineRunnerService", CommandLineRunnerService.class);
        commandLineRunnerService.reportLogin("yty");
    }

    @Override
    public void run(String... args) throws Exception {
        System.out.println("container just created: codes will be run");
    }
}
